project:
  type: website
  output-dir: docs

website:
  title: "Jordan Zhu"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Fengz924
      - icon: linkedin
        href: https://www.linkedin.com/in/feng-zhu-a79a73267/

format:
  html:
    theme: flatly
    css: styles.css

