project:
  type: website

website:
  title: "Timing and Duration Analysis of Solar Eclipses Across U.S. States in 2024"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Fengz924
format:
  html:
    theme:
      light: ["#f8f9fa", "#343a40"]
    css: styles.css
